<?php

/**
 * BaseDocumentType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $name
 * @property Doctrine_Collection $Documents
 * 
 * @method varchar             getName()      Returns the current record's "name" value
 * @method Doctrine_Collection getDocuments() Returns the current record's "Documents" collection
 * @method DocumentType        setName()      Sets the current record's "name" value
 * @method DocumentType        setDocuments() Sets the current record's "Documents" collection
 * 
 * @package    flux_docs
 * @subpackage model
 * @author     Gaspar Rajoy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDocumentType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('document_type');
        $this->hasColumn('name', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Document as Documents', array(
             'local' => 'id',
             'foreign' => 'document_type_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}