default:
  http_metas:
    content-type: text/html

  metas:
    title:        Flux IT Docs
    language:     en

  stylesheets:    [main.css, bootstrap.css, jquery-ui.css, ../sfTwitterBootstrapPlugin/css/style.css]

  javascripts:    
    - jquery
    - jquery-ui
    - bootstrap
    - ../sfTwitterBootstrapPlugin/js/jquery.tablesorter.min.js
    - ../sfTwitterBootstrapPlugin/js/application.js
    - ../sfTwitterBootstrapPlugin/js/bootbox/bootbox.min.js
  has_layout:     true
  layout:         layout
signinSuccess:
  stylesheets: [signin-fix]
