generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardGroup
    theme:                 twitter
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_group
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        batch_actions: {}
        display:  [name, description]
        object_actions:
          _show: { action: _show }
          _edit: ~
          _delete: ~
      filter:
        display:  [name, description]
      form:
        display:  [name, description]
      edit:
        display:  [name, description]
      new: ~
      show:
        display:  [name, description]
        