generator:
  class: sfDoctrineGenerator
  param:
    model_class:           DocumentType
    theme:                 twitter
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          document_type
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        batch_actions: {}
        display:  [name]
      filter:
        display:  [name]
      form:
        display:  [name]        
      edit:    ~
      new:     ~
