generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 twitter
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [first_name, last_name, username, email_address]
        object_actions:
          _show: { action: _show }
          _edit: ~
          _delete: ~
      filter:
        display: [first_name, last_name, username, email_address, groups_list]
      form:    ~
      edit:
        display: [username, first_name, last_name, email_address, groups_list]
      new:
        display: [username, first_name, last_name, email_address, password, groups_list]
      show:
        display: [username, first_name, last_name, email_address]
