generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [first_name, last_name, username, email_address]
      filter:
        display: [first_name, last_name, username, email_address]
      form:    ~
      edit:    ~
      new:
        display: [username, first_name, last_name, email_address, password, groups_list]
