DocumentType:
  tableName: document_type
  actAs: [ TimeStampable:  ~ ]
  columns:
    name:  { type: varchar(255), notnull: true }

Document:
  tableName: document
  actAs: [ TimeStampable:  ~ ]
  columns:
    name:  { type: varchar(255), notnull: true }
    description:  { type: text, notnull: true }
    filename: { type: varchar(255), notnull: true }
    user_id:   { type: integer, notnull: true }
    group_id:   { type: integer, notnull: true }    
    document_type_id: { type: integer, notnull: true }
  relations:
    sfGuardUser: { onDelete: CASCADE, local: user_id, foreign: id, foreignAlias: UserDocuments }
    sfGuardGroup: { onDelete: CASCADE, local: group_id, foreign: id, foreignAlias: GroupDocuments }
    DocumentType: { onDelete: CASCADE, local: document_type_id, foreign: id, foreignAlias: Documents }




