generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Document
    theme:                 twitter
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          document
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        sf_guard_user: {label: Owner}
        sf_guard_group: {label: Group}
        created_at: {label: Upload date}
        name_path_link: {label: Name}
        user_id: {label: Owner}
      list:
        batch_actions: {}
        display: [name, created_at, document_type, sf_guard_user ]
        object_actions:
          _show: { action: _show }
          _edit: ~
          _delete: ~
      filter:
        display: [name, user_id, created_at, group_id]
      form:    ~
      edit:    ~
      new:     
        display: [name, description, filename, document_type_id, user_id, group_id]
      show:     
        display: [_name_path_link, created_at, sf_guard_user, description, sf_guard_group]
        
