generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Document
    theme:                 admin
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          document
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:
        display: [name, user_id, created_at]
      form:    ~
      edit:    ~
      new:     
        display: [name, description, filename, document_type_id, user_id, group_id]
